/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RickImport } from './routes/rick'
import { Route as MortyImport } from './routes/morty'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RickRoute = RickImport.update({
  id: '/rick',
  path: '/rick',
  getParentRoute: () => rootRoute,
} as any)

const MortyRoute = MortyImport.update({
  id: '/morty',
  path: '/morty',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/morty': {
      id: '/morty'
      path: '/morty'
      fullPath: '/morty'
      preLoaderRoute: typeof MortyImport
      parentRoute: typeof rootRoute
    }
    '/rick': {
      id: '/rick'
      path: '/rick'
      fullPath: '/rick'
      preLoaderRoute: typeof RickImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/morty': typeof MortyRoute
  '/rick': typeof RickRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/morty': typeof MortyRoute
  '/rick': typeof RickRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/morty': typeof MortyRoute
  '/rick': typeof RickRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/morty' | '/rick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/morty' | '/rick'
  id: '__root__' | '/' | '/morty' | '/rick'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MortyRoute: typeof MortyRoute
  RickRoute: typeof RickRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MortyRoute: MortyRoute,
  RickRoute: RickRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/morty",
        "/rick"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/morty": {
      "filePath": "morty.tsx"
    },
    "/rick": {
      "filePath": "rick.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
